title: NetSci2025
description: Jekyll theme for a conference website
baseurl: ""
url: https://Yiijie.github.io/Webpage_project



copyright: Place Holder
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
