title: NetSci2025 Test
description: Jekyll theme for a conference website
baseurl: "/Webpage_project"

url: https://Yiijie.github.io/Webpage_project



copyright: Place Holder
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
